import { fontSizes } from './fontSizes';
import { fontWeights } from './fontWeights';
import { letterSpacing } from './letterSpacing';
import { lineHeights } from './lineHeights';
import type { ThemeTypography } from './types';

export const typography: ThemeTypography = {
  sDisplayLG: {
    fontWeight: fontWeights.bold,
    fontSize: fontSizes.fontSize8,
    lineHeight: lineHeights.lineHeight7,
    letterSpacing: letterSpacing.letterSpacing0,
  },
  sDisplayMD: {
    fontWeight: fontWeights.bold,
    fontSize: fontSizes.fontSize7,
    lineHeight: lineHeights.lineHeight6,
    letterSpacing: letterSpacing.letterSpacing0,
  },
  sHeadingLG: {
    fontWeight: fontWeights.bold,
    fontSize: fontSizes.fontSize6,
    lineHeight: lineHeights.lineHeight5,
    letterSpacing: letterSpacing.letterSpacing0,
  },
  sHeadingMD: {
    fontWeight: fontWeights.bold,
    fontSize: fontSizes.fontSize5,
    lineHeight: lineHeights.lineHeight4,
    letterSpacing: letterSpacing.letterSpacing0,
  },
  sHeadingSM: {
    fontWeight: fontWeights.bold,
    fontSize: fontSizes.fontSize4,
    lineHeight: lineHeights.lineHeight4,
    letterSpacing: letterSpacing.letterSpacing0,
  },
  sBodyLGMedium: {
    fontWeight: fontWeights.medium,
    fontSize: fontSizes.fontSize5,
    lineHeight: lineHeights.lineHeight4,
    letterSpacing: letterSpacing.letterSpacing0,
  },
  sBodyMD: {
    fontWeight: fontWeights.regular,
    fontSize: fontSizes.fontSize4,
    lineHeight: lineHeights.lineHeight4,
    letterSpacing: letterSpacing.letterSpacing0,
  },
  sBodyMDMedium: {
    fontWeight: fontWeights.medium,
    fontSize: fontSizes.fontSize4,
    lineHeight: lineHeights.lineHeight4,
    letterSpacing: letterSpacing.letterSpacing0,
  },
  sBodyMDBold: {
    fontWeight: fontWeights.bold,
    fontSize: fontSizes.fontSize4,
    lineHeight: lineHeights.lineHeight4,
    letterSpacing: letterSpacing.letterSpacing0,
  },
  sBodySM: {
    fontWeight: fontWeights.regular,
    fontSize: fontSizes.fontSize3,
    lineHeight: lineHeights.lineHeight3,
    letterSpacing: letterSpacing.letterSpacing0,
  },
  sBodySMMedium: {
    fontWeight: fontWeights.medium,
    fontSize: fontSizes.fontSize3,
    lineHeight: lineHeights.lineHeight3,
    letterSpacing: letterSpacing.letterSpacing0,
  },
  sBodySMBold: {
    fontWeight: fontWeights.bold,
    fontSize: fontSizes.fontSize3,
    lineHeight: lineHeights.lineHeight3,
    letterSpacing: letterSpacing.letterSpacing0,
  },
  sBodyXS: {
    fontWeight: fontWeights.regular,
    fontSize: fontSizes.fontSize2,
    lineHeight: lineHeights.lineHeight2,
    letterSpacing: letterSpacing.letterSpacing1,
  },
  sBodyXSMedium: {
    fontWeight: fontWeights.medium,
    fontSize: fontSizes.fontSize2,
    lineHeight: lineHeights.lineHeight2,
    letterSpacing: letterSpacing.letterSpacing1,
  },
  sPageHeading: {
    fontWeight: fontWeights.bold,
    fontSize: fontSizes.fontSize6,
    lineHeight: lineHeights.lineHeight5,
    letterSpacing: letterSpacing.letterSpacing0,
  },
  sSectionHeading: {
    fontWeight: fontWeights.bold,
    fontSize: fontSizes.fontSize5,
    lineHeight: lineHeights.lineHeight4,
    letterSpacing: letterSpacing.letterSpacing0,
  },
  sButtonLabelMd: {
    fontWeight: fontWeights.medium,
    fontSize: fontSizes.fontSize4,
    lineHeight: lineHeights.lineHeight4,
    letterSpacing: letterSpacing.letterSpacing0,
  },
  sButtonLabelLg: {
    fontWeight: fontWeights.medium,
    fontSize: fontSizes.fontSize5,
    lineHeight: lineHeights.lineHeight4,
    letterSpacing: letterSpacing.letterSpacing0,
  },
  sAmountDisplayLg: {
    fontWeight: fontWeights.bold,
    fontSize: fontSizes.fontSize8,
    lineHeight: lineHeights.lineHeight7,
    letterSpacing: letterSpacing.letterSpacing0,
  },
  lDisplayLG: {
    fontWeight: fontWeights.medium,
    fontSize: fontSizes.fontSize10,
    lineHeight: lineHeights.lineHeight9,
    letterSpacing: letterSpacing.letterSpacing0,
  },
  lDisplayMD: {
    fontWeight: fontWeights.medium,
    fontSize: fontSizes.fontSize9,
    lineHeight: lineHeights.lineHeight8,
    letterSpacing: letterSpacing.letterSpacing0,
  },
  lHeadingLG: {
    fontWeight: fontWeights.bold,
    fontSize: fontSizes.fontSize7,
    lineHeight: lineHeights.lineHeight6,
    letterSpacing: letterSpacing.letterSpacing0,
  },
  lHeadingMD: {
    fontWeight: fontWeights.bold,
    fontSize: fontSizes.fontSize6,
    lineHeight: lineHeights.lineHeight5,
    letterSpacing: letterSpacing.letterSpacing0,
  },
  lHeadingSM: {
    fontWeight: fontWeights.bold,
    fontSize: fontSizes.fontSize5,
    lineHeight: lineHeights.lineHeight4,
    letterSpacing: letterSpacing.letterSpacing0,
  },
  lBodyLGMedium: {
    fontWeight: fontWeights.medium,
    fontSize: fontSizes.fontSize5,
    lineHeight: lineHeights.lineHeight4,
    letterSpacing: letterSpacing.letterSpacing0,
  },
  lBodyMD: {
    fontWeight: fontWeights.regular,
    fontSize: fontSizes.fontSize4,
    lineHeight: lineHeights.lineHeight4,
    letterSpacing: letterSpacing.letterSpacing0,
  },
  lBodyMDMedium: {
    fontWeight: fontWeights.medium,
    fontSize: fontSizes.fontSize4,
    lineHeight: lineHeights.lineHeight4,
    letterSpacing: letterSpacing.letterSpacing0,
  },
  lBodyMDBold: {
    fontWeight: fontWeights.bold,
    fontSize: fontSizes.fontSize4,
    lineHeight: lineHeights.lineHeight4,
    letterSpacing: letterSpacing.letterSpacing0,
  },
  lBodySM: {
    fontWeight: fontWeights.regular,
    fontSize: fontSizes.fontSize3,
    lineHeight: lineHeights.lineHeight3,
    letterSpacing: letterSpacing.letterSpacing0,
  },
  lBodySMMedium: {
    fontWeight: fontWeights.medium,
    fontSize: fontSizes.fontSize3,
    lineHeight: lineHeights.lineHeight3,
    letterSpacing: letterSpacing.letterSpacing0,
  },
  lBodySMBold: {
    fontWeight: fontWeights.bold,
    fontSize: fontSizes.fontSize3,
    lineHeight: lineHeights.lineHeight3,
    letterSpacing: letterSpacing.letterSpacing0,
  },
  lBodyXS: {
    fontWeight: fontWeights.regular,
    fontSize: fontSizes.fontSize2,
    lineHeight: lineHeights.lineHeight2,
    letterSpacing: letterSpacing.letterSpacing1,
  },
  lBodyXSMedium: {
    fontWeight: fontWeights.medium,
    fontSize: fontSizes.fontSize2,
    lineHeight: lineHeights.lineHeight2,
    letterSpacing: letterSpacing.letterSpacing1,
  },
  lPageHeading: {
    fontWeight: fontWeights.bold,
    fontSize: fontSizes.fontSize7,
    lineHeight: lineHeights.lineHeight6,
    letterSpacing: letterSpacing.letterSpacing0,
  },
  lSectionHeading: {
    fontWeight: fontWeights.bold,
    fontSize: fontSizes.fontSize6,
    lineHeight: lineHeights.lineHeight5,
    letterSpacing: letterSpacing.letterSpacing0,
  },
  lButtonLabelMd: {
    fontWeight: fontWeights.medium,
    fontSize: fontSizes.fontSize4,
    lineHeight: lineHeights.lineHeight4,
    letterSpacing: letterSpacing.letterSpacing0,
  },
  lButtonLabelLg: {
    fontWeight: fontWeights.medium,
    fontSize: fontSizes.fontSize5,
    lineHeight: lineHeights.lineHeight4,
    letterSpacing: letterSpacing.letterSpacing0,
  },
  lAmountDisplayLg: {
    fontWeight: fontWeights.medium,
    fontSize: fontSizes.fontSize10,
    lineHeight: lineHeights.lineHeight9,
    letterSpacing: letterSpacing.letterSpacing0,
  },
};
